#!/bin/bash

######################################################################
# testheap1_add tests four HeapMgr implementations.
# Executable files named testheapmgrgnu, testheapmgrkr,testheapmgrbase,
# and testheapmgr1 must exist before executing this script.
# To execute the script, simply type testheap1.
######################################################################

echo "       Executable          Test   Count   Size Time_m Time_f   Time        Mem"
./testheapimp ./testheapmgrgnu
./testheapimp ./testheapmgrkr
./testheapimp ./testheapmgrbase
./testheapimp ./testheapmgr1
# ./testheapimp ./testheapmgr2